const nobitex = require('./src/main')
// const nobitex = require('nobitex.js')
const { token } = require('./file.json')


// nobitex.Price({type:''}).then(res => console.log(res))
// nobitex.Trades({ type: '' }).then(res => console.log(res))
// nobitex.Market({ from: 'btc', to: 'usdt' }).then(res => console.log(res))
// nobitex.Global().then(res => console.log(res))
// nobitex.Account({ token }).then(res => console.log(res))
// nobitex.CreateWallet({ token, type: '' }).then(res => console.log(res))
// nobitex.AddCard({ token, CardNumber: '', BankName: '' }).then(res => console.log(res))
// nobitex.AddBankAccount({ token, CardNumber: '', Shaba: '', CardName: '' }).then(res => console.log(res))
// nobitex.AccountLimitations({ token }).then(res => console.log(res))
// nobitex.AccountWallets({ token }).then(res => console.log(res))
// nobitex.AccountBalance({ token, type: '' }).then(res => console.log(res))