exports.Price = require('./modules/Price.module.js')
exports.Trades = require('./modules/Trades.module.js')
exports.Market = require('./modules/Market.module.js')
exports.Global = require('./modules/Global.module.js')
exports.Account = require('./modules/Account.module.js')
exports.CreateWallet = require('./modules/CreateWallet.module.js')
exports.AddCard = require('./modules/AddCard.module.js')
exports.AddBankAccount = require('./modules/AddBankAccount.module.js')